modelmanager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^simapp/', include('simapp.urls', namespace="simapp", app_name='simapp')),
    
    # handle static files
    url(r'^$', RedirectView.as_view(url=r'simapp', permanent=False)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simapp/urls.py
from django.conf.urls import url

from simapp import views
from simapp.reports import sbml_report

urlpatterns = [
    url(r'^models/$', views.models, name='models'),
    url(r'^model/(?P<model_id>\d+)$', views.model, name='model'),
    url(r'^cores/$', views.cores, name='cores'),
    url(r'^simulations/(?P<status>\w+)$', views.simulations, name='simulations'),
    url(r'^simulations/$', views.simulations, name='simulations'),
    url(r'^simulation/(?P<simulation_id>\d+)$', views.simulation, name='simulation'),
    
    url(r'^report/(?P<model_pk>\d+)$', sbml_report.report, name='report'),
    
    url(r'^methods/$', views.methods, name='methods'),
    url(r'^method/(?P<method_id>\d+)$', views.method, name='method'),

    url(r'^results/$', views.results, name='results'),

    url(r'^tasks/$', views.tasks, name='tasks'),
    url(r'^task/(?P<task_id>\d+)$', views.task, name='task'),
    url(r'^task/T(?P<task_id>\d+)$', views.task_report, name='task_parameters'),
    url(r'^task/C(?P<task_id>\d+)$', views.task_report_csv, name='task_report_csv'),

    url(r'^about/$', views.about, name='about'),

    url(r'^$', views.models, name='index'),
]

simapp/views.py
from django.http.response import HttpResponse
from django.template import RequestContext
from django.shortcuts import get_object_or_404, render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from simapp.models import CompModel, Core, Simulation, Result, Task, Method
from simapp.reports.task_report import TaskReport

PAGINATE_ENTRIES = 50

# ===============================================================================
# Models
# ===============================================================================
def models(request):
    """ Models overview. """
    # no select related for reverse possible (i.e. the task)
    model_list = CompModel.objects.order_by("-pk")
    return render_to_response('simapp/models.html',
                              {'model_list': model_list},
                              context_instance=RequestContext(request))

def model(request, model_id):
    """ View of single model. """
    model = get_object_or_404(CompModel, pk=model_id)
    return render_to_response('simapp/model.html',
                              {'model': model},
                              context_instance=RequestContext(request))

# ===============================================================================
# Cores
# ===============================================================================
def cores(request):
    """ Cores overview. """
    core_list = Core.objects.order_by("-time")
    return render_to_response('simapp/cores.html',
                              {'core_list': core_list},
                              context_instance=RequestContext(request))


# ===============================================================================
# Tasks
# ===============================================================================
def tasks(request):
    """ Tasks overview. """
    task_list = Task.objects.order_by('pk').reverse()
    return render_to_response('simapp/tasks.html',
                              {'task_list': task_list},
                              context_instance=RequestContext(request))


def task(request, task_id):
    """ View of single task. """
    task = get_object_or_404(Task, pk=task_id)
    simulations = Simulation.objects.filter(task=task).order_by("-time_assign", "-time_create").prefetch_related('parameters', 'results').select_related('task', 'task__method', 'task__model')
    # simulations = task.simulations.all|slice:":50"

    return render_to_response('simapp/task.html',
                              {'task': task,
                               'simulations': simulations},
                              context_instance=RequestContext(request))

def task_report(request, task_id):
    """ Most of the logic belongs in the Parameterfile.
        Here only the view should be generated.
    """
    task = get_object_or_404(Task, pk=task_id)
    report = TaskReport(task)
    return render_to_response('simapp/task_report.html',
                              {'task': task,
                               'filepath': report.filepath(),
                               'df': report.dataframe},
                              context_instance=RequestContext(request))

def task_report_csv(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    report = TaskReport(task)
    content = report.csv_string()
    return HttpResponse(content, content_type='text/plain')


# ===============================================================================
# Methods
# ===============================================================================
def methods(request):
    """ Overview of simulation methods. """
    method_list = Method.objects.order_by("pk")
    return render_to_response('simapp/methods.html',
                              {'method_list': method_list},
                              context_instance=RequestContext(request))

def method(request, method_id):
    """ View of single simulation method. """
    method = get_object_or_404(Method, pk=method_id)
    return render_to_response('simapp/method.html',
                              {'method': method},
                              context_instance=RequestContext(request))

# ===============================================================================
# Simulations
# ===============================================================================
from simapp.models import SimulationStatus


def simulations(request, status='ALL'):
    """ Simulations overview. """
    if status == 'ALL':
        sim_list = Simulation.objects.all()
    else:
        status_type = SimulationStatus.rev_labels[status]
        sim_list = Simulation.objects.filter(status=status_type)
    sim_list = sim_list.order_by("-time_assign", "-time_create").prefetch_related('parameters', 'results').select_related('task', 'task__method', 'task__model')

    paginator = Paginator(sim_list, PAGINATE_ENTRIES)
    page = request.GET.get('page')
    try:
        simulation_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        simulation_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        simulation_list = paginator.page(paginator.num_pages)

    return render_to_response('simapp/simulations.html',
                              {
                                  'simulation_list': simulation_list,
                                  'status': status,
                              },
                              context_instance=RequestContext(request))


def simulation(request, simulation_id):
    """ Overview of single simulation. """
    sim = get_object_or_404(Simulation, pk=simulation_id)
    try:
        sim_previous = Simulation.objects.get(pk=(sim.pk - 1))
    except Simulation.DoesNotExist:
        sim_previous = None
    try:
        sim_next = Simulation.objects.get(pk=(sim.pk + 1))
    except Simulation.DoesNotExist:
        sim_next = None

    return render_to_response('simapp/simulation.html', {
        'sim': sim,
        'sim_previous': sim_previous,
        'sim_next': sim_next,
        },
        context_instance=RequestContext(request))


# ===============================================================================
# Results
# ===============================================================================
def results(request):
    """ Overview of Results. """
    results_all = Result.objects.all().select_related('simulation')
    paginator = Paginator(results_all, PAGINATE_ENTRIES)
    page = request.GET.get('page')
    try:
        result_list = paginator.page(page)
    except PageNotAnInteger:
        result_list = paginator.page(1)  # If page is not an integer, deliver first page.
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        result_list = paginator.page(paginator.num_pages)

    return render_to_response('simapp/results.html',
                              {'result_list': result_list},
                              context_instance=RequestContext(request))


# ===============================================================================
# About
# ===============================================================================
def about(request):
    """ Overview project information.
    Provide additional resources, links, explanation, background.
    """
    # TODO: update template
    return render_to_response('simapp/about.html', {},
                              context_instance=RequestContext(request))

simapp/templates/simapp/about.html
{% extends "simapp/base_generic.html" %}
{% load staticfiles %}

{% block content %}
    <h1>About</h1>
    <h2>Introduction</h2>
    <p>This project contains the database content of the the multiscale-galactose project.</p>
    <p>Methods and models are described in the upcoming publication "Multi-scale modelling of hepatic liver galactose
        metabolism".
        <br/>
        If you have any questions, thoughts, concerns or feedback, please don't hesitate to email
        <a href="mailto:konigmatt@googlemail.com">konigmatt[at]googlemail.com</a>.
    </p>

    <h2>Open Source</h2>
    <p>This project is open source and shared under a Creative Commons License. All project code and data is available
        from<br/>
        <a href="https://github.com/matthiaskoenig/multiscale-galactose"><code>https://github.com/matthiaskoenig/multiscale-galactose</code></a>.
    </p>
    <p>
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License"
                                                                                    style="border-width:0"
                                                                                    src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png"/></a><br/>This
        work by <a xmlns:cc="http://creativecommons.org/ns#" href="https://www.livermetabolism.com"
                   property="cc:attributionName" rel="cc:attributionURL">Matthias Koenig</a> is licensed under a <a
            rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike
        4.0 International License</a>.
    </p>

    <h2>Funding</h2>
    <p>This work was funded 2011-2015 by the Virtual Liver Network VLN.</p>
    <p>
        <a href="http://www.virtual-liver.de" target="_blank"><img src="{% static 'simapp/images/vln.png' %}"
                                                                   height="30" alt="Virtual Liver Network"/></a>
        <a href="http://www.charite.de" target="_blank"><img src="{% static 'simapp/images/charite.png' %}" height="30"
                                                             alt="Charite Berlin"/></a>
    </p>
{% endblock %}

simapp/templates/simapp/base_generic.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="Multiscale-model of hepatic metabolism">
	<meta name="author" content="Matthias Koenig">
      <meta http-equiv="refresh" content="60" />
    <link rel="icon" href="{% static 'simapp/images/favicon.ico' %}">
    <title>{% block title %}Multiscale-Galactose{% endblock %}</title>

    <!-- CSS -->
      <link rel="stylesheet" type="text/css" href="{% static 'simapp/css/bootstrap.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'simapp/css/dataTables.bootstrap.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'simapp/css/my.css' %}" >
	
    <!-- JAVASCRIPT -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


  <script type="text/javascript" language="javascript" src="{%  static 'simapp/js/jquery-1.11.1.min.js' %}"></script>
      <script type="text/javascript" language="javascript" src="{%  static 'simapp/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{%  static 'simapp/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{%  static 'simapp/js/dataTables.bootstrap.js' %}"></script>


    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $('#table_items').dataTable({
                "iDisplayLength": 25
            });
            $('#table_parameters').dataTable({
                paging: false
            } );
        });
    </script>

	
  </head>
<body>
 <!-- Fixed navbar -->
 <nav class="navbar navbar-fixed-top navbar-inverse">
     <div class="container">

         <div class="navbar-header">
             <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                     aria-expanded="false" aria-controls="navbar">
                 <span class="sr-only">Toggle navigation</span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="{% url 'simapp:models' %}">Model-Manager</a>
         </div>

         <div id="navbar" class="navbar-collapse collapse">
             <ul class="nav navbar-nav">
                 <li><a href="{% url 'simapp:models' %}">Models</a></li>

                 <li><a href="{% url 'simapp:tasks' %}">Tasks</a></li>
                 <li><a href="{% url 'simapp:methods' %}">Methods</a></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Simulations <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'simapp:simulations' 'ALL' %}">All</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Simulation Status</li>
                <li><a href="{% url 'simapp:simulations' 'DONE' %}">Done</a></li>
                <li><a href="{% url 'simapp:simulations' 'ASSIGNED' %}">Assigned</a></li>
                <li><a href="{% url 'simapp:simulations' 'UNASSIGNED' %}">Unassigned</a></li>
                <li><a href="{% url 'simapp:simulations' 'ERROR' %}">Error</a></li>
              </ul>
            </li>


                 <li><a href="{% url 'simapp:results' %}">Results</a></li>
                 <li><a href="{% url 'simapp:cores' %}">Cores</a></li>


             </ul>
             <ul class="nav navbar-nav navbar-right">
                 <li><a href="{% static 'schema/index.html' %}">DB schema</a></li>

                 <li><a href="{% url 'simapp:about' %}">About</a></li>
                 <li class="active"><a href="{% url 'admin:index' %}">Admin</a></li>
             </ul>
         </div>
         <!--/.nav-collapse -->
     </div>
 </nav>

 <!-- CONTENT -->
    <div class="container">
		<div class="content">
		{% block content %}{% endblock %}
		</div>
	
		<!-- FOOTER -->
		<div class="footer">
		<hr />
	    	<p>&copy; 2016 Matthias Koenig.
               <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a><br />This work by <a xmlns:cc="http://creativecommons.org/ns#" href="https://www.livermetabolism.com" property="cc:attributionName" rel="cc:attributionURL">Matthias Koenig</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
                <br />
	    	Powered by <a href="https://www.djangoproject.com"  target="_blank"><img src="{% static 'simapp/images/django.png' %}" height="15" alt="django" /></a> and
                bootstrap <a href="http://getbootstrap.com/"  target="_blank"><img src="{% static 'simapp/images/bootstrap.png' %}" height="15" alt="bootstrap" /></a>.
        	Source available on <a href="https://github.com/matthiaskoenig/multiscale-galactose/" target="_blank"><img src="{% static 'simapp/images/github.png' %}" height="20" alt="GitHub"/></a>.
        	</p>
    	</div>


    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    
  </body>
</html>

simapp/templates/simapp/cores.html
{% extends "simapp/base_generic.html" %}
{% load staticfiles %}
{% load macros %}
{% loadmacros "simapp/macros.html" %}

<!------------------------------------------------------->
<!--  CORES											   -->
<!------------------------------------------------------->
{% block content %}
    <h3>Cores</h3>
    <table id="table_items" class="table table-condensed table-responsive">
        <thead>
            {% usemacro core_header %}
        </thead>
        <tbody>
            {% for core in core_list %}
                {% usemacro core_content %}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

simapp/templates/simapp/macros.html
{% load staticfiles %}
{% load macros %}
<!------------------------------------------------------->
<!--  SIMULATION 									   -->
<!------------------------------------------------------->
{% macro simulation_header %}
    <tr>
        <th>pk</th>
        <th>model</th>
        <th>task</th>
        <th>method</th>
        <th>parameters</th>
        <th>status</th>
        <th>duration</th>
        <th>core</th>
        <th>results</th>
    </tr>
{% endmacro %}
{% macro simulation_content %}
    <tr class="{% if sim.is_done %}success{% else %}warning{% endif %}">
        <td><a href="{% url 'simapp:simulation' sim.pk %}">{{ sim.pk }}</a></td>
        <td><a href="{% url 'simapp:model' sim.task.model.pk %}">{{ sim.task.model.model_id }}</a></td>
        <td><a href="{% url 'simapp:task' sim.task.pk %}">{{ sim.task }}</a></td>
        <td><a href="{% url 'simapp:method' sim.task.method.pk %}">{{ sim.task.method }}</a></td>
        <td>{% for p in sim.parameters.all %}{{ p }}<br/>{% endfor %}</td>
        <td>{{ sim.status_str }}</td>
        <td>{{ sim.duration }}</td>
        <td>{{ sim.core }}</td>
        <td> {% if sim.is_done %}
            {%  for result in sim.results.all %}
                <a href="{{ result.file.url }}" target="_blank">{{ result }}</a><br/>
            {% endfor %}

        {% endif %}
        </td>
    </tr>
{% endmacro %}

<!------------------------------------------------------->
<!--  PARAMETER 									   -->
<!------------------------------------------------------->
{% macro parameter_header %}
    <tr>
        <th>id</th>
        <th>value</th>
        <th>unit</th>
        <th>type</th>
    </tr>
{% endmacro %}
{% macro parameter_content %}
    <tr>
        <td>{{ pars.key }}</td>
        <td>{{ pars.value }}</td>
        <td>{{ pars.unit }}</td>
        <td>{{ pars.parameter_type_str }}</td>
    </tr>
{% endmacro %}

<!------------------------------------------------------->
<!--  MODEL											   -->
<!------------------------------------------------------->
{% macro model_header %}
    <tr>
        <th>pk</th>
        <th>model</th>
        <th>file</th>
        <th>report</th>
        <th>tasks</th>
        <th>md5</th>
    </tr>
{% endmacro %}
{% macro model_content %}
    <tr>
        <td><a href="{% url 'simapp:model' model.pk %}">{{ model.pk }}</a></td>
        <td>{{ model }}</td>
        <td><a href="{{ model.file.url }}" target="_blank">
            {% if model.is_sbml %}
                <img height="12" src="{% static 'simapp/images/sbml.png' %}">
            {%  elif model.is_cellml %}
                <img height="12" src="{% static 'simapp/images/cellml.png' %}">
            {%  else %}
                <img height="12" src="{% static 'simapp/images/unknown.png' %}">
            {% endif %}
        </a></td>
        <td>{% if model.is_sbml %}
            <a href="{% url 'simapp:report' model.pk %}" target="_blank">
            <img height="12" src="{% static 'simapp/images/html5.png' %}"></a>
            {% endif %}
        </td>
        <td>{% for task in model.tasks.all %}
            <a href="{% url 'simapp:task' task.pk %}">{{ task }}</a>: {{ task.info }}<br/>
            {% endfor %}
            </td>
        <td>{{ model.md5 }}</td>
    </tr>
{% endmacro %}

<!------------------------------------------------------->
<!--  RESULT    									   -->
<!------------------------------------------------------->
{% macro result_header %}
    <tr>
        <th>pk</th>
        <th>sim</th>
        <th>type</th>
        <th>icon</th>
        <th>file</th>
    </tr>
{% endmacro %}
{% macro result_content %}
    <tr>
        <td>{{ result.pk }}</td>
        <td><a href="{% url 'simapp:simulation' result.simulation.pk %}">{{ result.simulation }}</a></td>
        <td>{{ result.result_type_str }}</td>
        <td><a href="{{ result.file.url }}"><img src="{% static 'simapp/images/hdf5.png' %}" height="15"/></a></td>
        <td><a href="{{ result.file.url }}">{{ result.file.name }}</a></td>
    </tr>
{% endmacro %}

<!------------------------------------------------------->
<!--  METHOD     									   -->
<!------------------------------------------------------->
{% macro method_header %}
    <tr>
        <th>pk</th>
        <th>method_type</th>
        <th>settings</th>
    </tr>
{% endmacro %}

{% macro method_content %}
    <tr>
        <td>{{ method.pk }}</td>
        <td>{{ method.method_type_str }}</td>
        <td>{% for s in method.settings.all %}
            {{ s.key_str }} = {{ s.value }}<br/>
        {% endfor %}</td>
    </tr>
{% endmacro %}

<!------------------------------------------------------->
<!--  TASK 											   -->
<!------------------------------------------------------->
{% macro task_header %}
    <tr>
        <th>pk</th>
        <th>model</th>
        <th>status</th>
        <th>simulations</th>
        <th>priority</th>
        <th>model</th>
        <th>parameters</th>
        <th>method</th>
        <th>info</th>
    </tr>
{% endmacro %}
{% macro task_content %}
    <tr class="{% if task.is_done %}success{% else %}warning{% endif %}">
        <td><a href="{% url 'simapp:task' task.pk %}">{{ task.pk }}</a></td>
        <td>{{ task.model }} </td>
        <td>{{ task.status_str }}</td>
        <td>
            <strong>{{ task.sim_count }}</strong>
            [<span class="text-success">{{ task.done_count }}</span>|<span
                class="ASSIGNED">{{ task.assigned_count }}</span>|<span
                class="UNASSIGNED">{{ task.unassigned_count }}</span>|<span
                class="text-danger">{{ task.error_count }}</span>]</td>
        <td>{{ task.priority }}</td>
        <td>{{ task.sbml_model.model_id }}
            <a href="{{ task.sbml_model.file.url }}" target="_blank"><img height="12" src="{% static 'simapp/images/sbml.png' %}"></a>
            <a href="{% url 'simapp:report' task.model.pk %}" target="_blank"><img height="12" src="{% static 'simapp/images/html5.png' %}"></a>
            </td>
        <td><a href="{% url 'simapp:task_parameters' task.pk %}" target="_blank">
            <img height="12" src="{% static 'simapp/images/params_small.png' %}"></a></td>
        <td><strong>{{ task.method }}({{ task.method.method_type_str }})</strong><br/>
            {% for s in task.method.settings.all %}
                {{ s.key_str }} = {{ s.value }}<br/>
            {% endfor %}</td>
        <td width="400px">{{ task.info }}</td>
    </tr>
{% endmacro %}

<!------------------------------------------------------->
<!--  CORE      									   -->
<!------------------------------------------------------->
{% macro core_header %}
    <tr>
        <th>id</th>
        <th>computer</th>
        <th>ip</th>
        <th>cpu</th>
        <th>time</th>
        <th>is active</th>
    </tr>
{% endmacro %}
{% macro core_content %}
    <tr class="{% if core.active %}success{% else %}warning{% endif %}">
        <td>{{ core.id }}</td>
        <td>{{ core.computer }}</td>
        <td>{{ core.ip }}</td>
        <td>{{ core.cpu }}</td>
        <td>{{ core.time }}</td>
        <td>{{ core.active }}</td>
    </tr>
{% endmacro %}

<!------------------------------------------------------->
<!--  PAGINATION  									   -->
<!------------------------------------------------------->
{% macro pagination %}
  <div class="pagination">
    <span class="step-links">
        {% if items.has_previous %}
            <a href="?page={{ items.previous_page_number }}">previous</a>
        {% else %}
         previous
        {% endif %}
		 | 
        {% if items.has_next %}
            <a href="?page={{ items.next_page_number }}">next</a>
        {% endif %}
        
        <span class="current">
           [{{ items.number }} of {{ items.paginator.num_pages }}]
        </span>
    </span>
	</div>
{% endmacro %}

simapp/templates/simapp/method.html
{% extends "simapp/base_generic.html" %}
{% load macros %}
{% loadmacros "simapp/macros.html" %}


<!------------------------------------------------------->
<!--  METHOD    									   -->
<!------------------------------------------------------->
{% block content %}
    <h3>Method ({{ method.pk }})</h3>
    <table id="table_items" class="table table-condensed table-responsive">
        <thead>
            {% usemacro method_header %}
        </thead>
        <tbody>
            {% usemacro method_content %}
        </tbody>
    </table>
{% endblock %}

simapp/templates/simapp/methods.html
{% extends "simapp/base_generic.html" %}
{% load macros %}
{% loadmacros "simapp/macros.html" %}


<!------------------------------------------------------->
<!--  METHODS										   -->
<!------------------------------------------------------->
{% block content %}
    <h3>Methods</h3>
    <table class="table table-condensed table-responsive">
        <thead>
            {% usemacro method_header %}
        </thead>
        <tbody>
            {% for method in method_list %}
                {% usemacro method_content %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

simapp/templates/simapp/model.html
{% extends "simapp/base_generic.html" %}
{% load staticfiles %}
{% load macros %}
{% loadmacros "simapp/macros.html" %}

<!------------------------------------------------------->
<!--  MODELS										   -->
<!------------------------------------------------------->
{% block content %}
    <h3>Model ({{ model.pk }})</h3>
    <table class="table table-condensed table-responsive">
        <thead>
            {% usemacro model_header %}
        </thead>
        <tbody>
            {% usemacro model_content %}
        </tbody>
    </table>

    <h3>Tasks</h3>
    <table id="table_items" class="table table-condensed table-responsive">
        <thead>
            {% usemacro task_header %}
        </thead>
        <tbody>
        {% for task in model.tasks.all %}
            {% usemacro task_content %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

simapp/templates/simapp/models.html
{% extends "simapp/base_generic.html" %}
{% load staticfiles %}
{% load macros %}
{% loadmacros "simapp/macros.html" %}

<!------------------------------------------------------->
<!--  MODELS										   -->
<!------------------------------------------------------->
{% block content %}
    <h3>Models</h3>
    <table id="table_items" class="table table-condensed table-responsive">
        <thead>
            {% usemacro model_header %}
        </thead>
        <tbody>
        {% for model in model_list %}
                {% usemacro model_content %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

simapp/templates/simapp/results.html
{% extends "simapp/base_generic.html" %}
{% load macros %}
{% loadmacros "simapp/macros.html" %}

<!------------------------------------------------------->
<!--  RESULTS										   -->
<!------------------------------------------------------->
{% block content %}
    <table id="table_items" class="table table-condensed table-responsive">
        <caption>Results</caption>
        <thead>
            {% usemacro result_header %}
        </thead>
        <tbody>
            {% for result in result_list %}
                {% usemacro result_content %}
            {% endfor %}
        </tbody>
    </table>

    {% if result_list %}
        {% with items=result_list %}
            {% usemacro pagination %}
        {% endwith %}
    {% endif %}
{% endblock %}

simapp/templates/simapp/simulations.html
{% extends "simapp/base_generic.html" %}
{% load macros %}
{% loadmacros "simapp/macros.html" %}

<!------------------------------------------------------->
<!--  SIMULATIONS									   -->
<!------------------------------------------------------->
{% block content %}
    <h3>Simulations</h3>
    <table id="table_items" class="table table-condensed table-responsive">
        <thead>
            {% usemacro simulation_header %}
        </thead>
        <tbody>
            {% for sim in simulation_list %}
                {% usemacro simulation_content %}
            {% endfor %}
        </tbody>
    </table>

    {% if simulation_list %}
        {% with items=simulation_list %}
            {% usemacro pagination %}
        {% endwith %}
    {% endif %}
{% endblock %}

simapp/templates/simapp/task_report.html
{% extends "simapp/base_generic.html" %}
{% load macros %}
{% loadmacros "simapp/macros.html" %}
{% load staticfiles %}
{% load Parameter_filters %}
<!------------------------------------------------------->
<!--  TASK  										   -->
<!------------------------------------------------------->
{% block content %}
    {% comment %}
    <h1>Task ({{ task.pk }})</h1>
    <table class="table table-condensed table-responsive">
    <thead>
        {% usemacro task_header %}
    </thead>
        <tbody>
            {% usemacro task_content %}
        </tbody>
    </table>

    <!-- Simulations for task -->
    <table id="table_items" class="table table-condensed table-responsive">
    <thead>
        {% usemacro simulation_header %}
    </thead>
    <tbody>
        {% for sim in task.simulations.all|slice:":50" %}
            {% usemacro simulation_content %}
        {% endfor %}
    </tbody>
    </table>

    {% endcomment %}
    <a href="{% url 'simapp:task_report_csv' task.pk %}"><img src="{% static 'simapp/images/csv.png' %}" height="25"/></a>
    {{ df | dataframe_to_html | safe }}


{% endblock %}